# -*- coding: utf-8 -*-
"""Calculadora Basica .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wEuNzpIC2OWDNsPAmV-pXtBjzCKVL496
"""

def Menu():
  """FUNCION QUE MUESTRA EL MENU"""
print("""
CALCULADORA

MENU

1)SUMA
2)RESTA
3)MULTIPLICACION
4)DIVISION
5)SALIR""" )

n1=int(input("Introduce un número:"))
n2=int(input("Introduce un segundo número:" ))

opcion= 0
opcion =int(input("Elige una opción: "))
if opcion == 1:
       print("")
       print("RESULTADO: La suma de ",n1,"+",n2, "es igual a",n1+n2)
elif opcion ==2:
        print("")
        print("RESULTADO: La resta de ",n1,"-",n2,"es igual a",n1-n2)
elif opcion ==3:
        print("")  
        print("RESULTADO: El producto de ",n1,"*",n2,"es igual a", n1*n2)   
elif opcion ==4:
        print("")
        print("RESULTADO: El cociente de ", n1,"/",n2, "es igual a", n1/n2)  
elif opcion == 5:
        print("")
        print("Hasta Pronto")
else:
        print("Opción Incorrecta")